name: Deploy to 10Web

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to 10Web via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.TENWEB_SFTP_HOST }}
        username: ${{ secrets.TENWEB_SFTP_USER }}
        password: ${{ secrets.TENWEB_SFTP_PASSWORD }}
        port: ${{ secrets.TENWEB_SFTP_PORT }}
        protocol: sftp
        local-dir: ./wp-content/themes/norvault-theme/
        server-dir: /public_html/wp-content/themes/norvault-theme/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**

    - name: Create Permalinks Fix Script
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.TENWEB_SFTP_HOST }}
        username: ${{ secrets.TENWEB_SFTP_USER }}
        password: ${{ secrets.TENWEB_SFTP_PASSWORD }}
        port: ${{ secrets.TENWEB_SFTP_PORT }}
        script: |
          cd public_html
          # Create fix script
          cat > fix-permalinks.php << 'EOF'
          <?php
          require_once('wp-load.php');
          flush_rewrite_rules(true);
          echo "Permalinks geflusht!";
          ?>
          EOF
          
          # Run it via PHP
          php fix-permalinks.php
          
          # Clean up
          rm -f fix-permalinks.php
